version: '2'

name: dependencies-compose

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    hostname: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password1234

volumes:
  esdata1:
    driver: local

networks:
  elasticnet: {}
